server:
    port: 8082
eureka:
    client:
       region: default
       registryFetchIntervalSeconds: 5
       serviceUrl:
          defaultZone: http://localhost:8888/eureka
    instance:
      metadataMap:
          instanceId: ${spring.application.name}:${random.value}      