spring:
    batch.job.enabled: false
    datasource:
        url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
        username: sa
        password: 
      
        driver-class-name: org.h2.Driver
        dbcp.test-while-idle: true
        
        
jpa:
    hibernate:
        ddl-auto: none
        show-sql: false
        database-platform: org.hibernate.dialect.H2Dialect