spring:
    batch.job.enabled: false
    datasource:
        url: jdbc:postgresql://localhost:5432/NikoHab?stringtype=unspecified
        username: Niko
        password:
   
jpa:
    hibernate:
        ddl-auto: none
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        
server:       
     port: 8089