spring:
    batch.job.enabled: false
    datasource:
        url: jdbc:sqlserver://192.168.0.101:1433;databaseName=isis_2
        username: sa
        password: password
        maximum-pool-size: 100
        max-idle: 25
        min-idle: 5
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        dbcp.test-while-idle: true
        time-between-eviction-runs-millis: 3600000
        dbcp.validation-query: SELECT 1
        
jpa:
    hibernate:
        ddl-auto: none
        show-sql: false
        database-platform: org.hibernate.dialect.SQLServerDialect