server:
    port: 8080

eureka:
    client:
        region: default    
        registryFetchIntervalSeconds: 5
        serviceUrl:
             defaultZone: http://localhost:8888/eureka
zuul:
   routes:
       producer-service:
            path: /producer-service/**

       discovery:
            path: /eureka/**
            url: http://localhost:8888
hystrix:
  command:    
      default:
        execution:
           isolation:
              thread:
                 timeoutInMilliseconds: 20000        

logging:
    level:
       org.springframework:
           web: debug
           cloud:
              netflix:
                 zuul: debug

