server:
    port: 8079
zuul:
    routes:
      producer.url: http://localhost:0
eureka:
   client:
      serviceUrl:
          defaultZone: http://localhost:8888/eureka
   instance:
      metadataMap:
          instanceId: ${spring.application.name}:${random.value}          
