 
  DROP TABLE niko.EVENT_JOB_AUDIT       IF EXISTS
  DROP TABLE niko.EVENT_JOB_INFO        IF EXISTS 
  DROP TABLE niko.EVENT_JOB             IF EXISTS
  DROP TABLE niko.event                 IF EXISTS
  DROP TABLE niko.BATCH_PROCESSOR_NODE  IF EXISTS
 
  CREATE TABLE niko.BATCH_PROCESSOR_NODE
 (
     BATCH_PROCESSOR_NODE_ID int NOT NULL,
     NAME character varying(50) NOT NULL,
     CONSTRAINT BATCH_PROCESSOR_NODE_ID_PK PRIMARY KEY (BATCH_PROCESSOR_NODE_ID)
 )



 CREATE TABLE niko.EVENT
 (
     EVENT_ID int NOT NULL,
     NAME character varying(50) NOT NULL,
     CONSTRAINT EVENT_ID_PK PRIMARY KEY (EVENT_ID)
 )

 ALTER TABLE niko.EVENT ADD CONSTRAINT EVENT_NAME_UNQ UNIQUE (NAME)


 CREATE TABLE niko.EVENT_JOB
 (
    EVENT_JOB_ID bigint NOT NULL,
    EVENT_ID int,
 	NAME character varying(30) not null,
 	START_DATE timestamp without time zone NOT NULL,
 	END_DATE timestamp without time zone NOT NULL,
 	CREATED_DATE timestamp without time zone NOT NULL,
 	CREATED_BY character varying(20) not null,
 	LAST_UPDATED_DATE timestamp without time zone,
 	LAST_MODIFY_BY character varying(20),
     CONSTRAINT EVENT_JOB_ID_PK PRIMARY KEY (EVENT_JOB_ID)
 )
 ALTER TABLE niko.EVENT_JOB ADD CONSTRAINT  EVENT_JOB_ID_NAME_UNQ UNIQUE (EVENT_JOB_ID,NAME)

 ALTER TABLE niko.EVENT_JOB ADD CONSTRAINT EVENT_ID_FK FOREIGN KEY (EVENT_ID) REFERENCES niko.EVENT (EVENT_ID) 

 CREATE TABLE niko.EVENT_JOB_INFO (
    EVENT_JOB_INFO_ID bigint NOT NULL,
    EVENT_JOB_ID int not null,
 	JOB_EXECUTION_ID bigint,
 	MAX_REPEAT int not null,
 	REPEATED int,
  	STATUS character varying(20),
 	BATCH_PROCESSOR_NODE_ID bigint not null,
 	KEY_STRING character varying(250),
  	KEY_LONG bigint, 
	
 	CREATED_DATE timestamp without time zone NOT NULL,
  	CREATED_BY character varying(20) not null,
 	LAST_UPDATED_DATE timestamp without time zone,
  	LAST_MODIFY_BY character varying(20),

     CONSTRAINT EVENT_JOB_INFO_ID_PK  PRIMARY KEY (EVENT_JOB_INFO_ID)
  )

 ALTER TABLE niko.EVENT_JOB_INFO ADD CONSTRAINT EVENT_JOB_ID_FK FOREIGN KEY (EVENT_JOB_ID) REFERENCES niko.EVENT_JOB (EVENT_JOB_ID)
 ALTER TABLE niko.EVENT_JOB_INFO ADD CONSTRAINT JOB_EXECUTION_ID_FK FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES public.BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) 
 ALTER TABLE niko.EVENT_JOB_INFO ADD CONSTRAINT BATCH_PROCESSOR_NODE_ID_FK FOREIGN KEY (BATCH_PROCESSOR_NODE_ID) REFERENCES niko.BATCH_PROCESSOR_NODE (BATCH_PROCESSOR_NODE_ID) 


CREATE TABLE niko.EVENT_JOB_AUDIT
 (
    EVENT_JOB_AUDIT_ID bigint NOT NULL,
	EVENT_JOB_INFO_ID bigint  NOT NULL,		
	CREATED_DATE timestamp without time zone NOT NULL,
	CREATED_BY character varying(20) not null,
	PRIMARY_ID character varying(25),
	DESCRIPTION character varying(100),
	MESSAGE character varying(250),

			
   CONSTRAINT EVENT_JOB_AUDIT_PK  PRIMARY KEY (EVENT_JOB_AUDIT_ID)
 )

ALTER TABLE niko.EVENT_JOB_AUDIT ADD CONSTRAINT EVENT_JOB_INFO_ID_FK FOREIGN KEY (EVENT_JOB_INFO_ID) REFERENCES niko.EVENT_JOB_INFO (EVENT_JOB_INFO_ID) 


